<!-- formCadastro.phtml -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulário de Cadastro</title>
</head>

<body>
    <h2>Cadastro de Clientes</h2>

    <form action="/salvarCliente" method="post">
        <label for="nome">Nome:</label>
        <input type="text" name="nome" required>
        <br>

        <label for="email">E-mail:</label>
        <input type="email" name="email" required>
        <br>

        <label for="senha">Senha:</label>
        <input type="password" name="senha" required>
        <br>

        <input type="submit" value="Cadastrar">
    </form>
</body>

</html>